@base_url=http://localhost:8000/api/v1

# --- Password

###
# @name generate-password
POST {{base_url}}/passwords/generate
Content-Type: application/json

{
  "length": 16,
  "uppercase": true,
  "lowercase": true,
  "numbers": true,
  "symbols": true
}


# --- Utils

###
# @name get-version
GET {{base_url}}/health/version
Content-Type: application/json

###
# @name healthcheck
GET {{base_url}}/health
Content-Type: application/json
