version: "3.9"

services:
  backend-api:
    build: .
    # working_dir: /code/app
    environment:
      DEBUG: 1
    volumes:
      - ./app:/main
    ports:
      - "8000:8000"
    restart: on-failure